-- Electricity Bill Splitter schema
-- Apply with `supabase db push` or paste into the Supabase SQL editor.

create extension if not exists pgcrypto;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

comment on column public.profiles.is_admin is
  'Server-authoritative administrator flag. Never derive authorization from client metadata.';

create table public.tariff_versions (
  id uuid primary key default gen_random_uuid(),
  version bigint generated by default as identity unique not null,
  label text not null check (length(btrim(label)) between 1 and 120),
  effective_from date not null unique,
  slabs jsonb not null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now()
);

create type public.monthly_bill_status as enum ('draft', 'published');

create table public.monthly_bills (
  id uuid primary key default gen_random_uuid(),
  bill_year integer not null check (bill_year between 2020 and 9999),
  bill_month integer not null check (bill_month between 1 and 12),
  total_bill numeric(14,2) not null check (total_bill > 0),
  status public.monthly_bill_status not null default 'draft',
  tariff_version_id uuid not null references public.tariff_versions(id) on delete restrict,
  tariff_snapshot jsonb not null,
  calculation_snapshot jsonb not null,
  people_snapshot jsonb not null,
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  updated_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  constraint monthly_bills_one_per_month unique (bill_year, bill_month),
  constraint monthly_bills_publication_time check (
    (status = 'draft' and published_at is null)
    or (status = 'published' and published_at is not null)
  ),
  constraint monthly_bills_snapshots_are_structured check (
    jsonb_typeof(tariff_snapshot) = 'array'
    and jsonb_typeof(calculation_snapshot) = 'object'
    and jsonb_typeof(people_snapshot) = 'array'
    and jsonb_array_length(people_snapshot) > 0
  )
);

create table public.audit_logs (
  id bigint generated always as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  table_name text not null,
  row_id uuid,
  old_record jsonb,
  new_record jsonb,
  occurred_at timestamptz not null default now()
);

create index tariff_versions_effective_from_idx
  on public.tariff_versions (effective_from desc);
create index monthly_bills_status_month_idx
  on public.monthly_bills (status, bill_year desc, bill_month desc);
create index monthly_bills_tariff_version_idx
  on public.monthly_bills (tariff_version_id);
create index audit_logs_record_idx
  on public.audit_logs (table_name, row_id, occurred_at desc);
create index audit_logs_actor_idx
  on public.audit_logs (actor_id, occurred_at desc);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(
    (select p.is_admin from public.profiles p where p.id = auth.uid()),
    false
  );
$$;

comment on function public.is_admin() is
  'Returns whether the current authenticated user has server-side admin authorization.';

create or replace function public.validate_tariff_slabs(value jsonb)
returns boolean
language plpgsql
immutable
set search_path = pg_catalog, pg_temp
as $$
declare
  item jsonb;
  item_index integer := 0;
  item_count integer;
begin
  if jsonb_typeof(value) <> 'array' or jsonb_array_length(value) = 0 then
    return false;
  end if;

  item_count := jsonb_array_length(value);
  for item in select * from jsonb_array_elements(value)
  loop
    item_index := item_index + 1;
    if jsonb_typeof(item) <> 'object'
      or jsonb_typeof(item -> 'rate') <> 'number'
      or (item ->> 'rate')::numeric <= 0
      or not (item ? 'units') then
      return false;
    end if;

    if item_index = item_count then
      if jsonb_typeof(item -> 'units') <> 'null' then
        return false;
      end if;
    elsif jsonb_typeof(item -> 'units') <> 'number'
      or (item ->> 'units')::numeric <= 0 then
      return false;
    end if;
  end loop;

  return true;
exception when others then
  return false;
end;
$$;

alter table public.tariff_versions
  add constraint tariff_versions_valid_slabs
  check (public.validate_tariff_slabs(slabs));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

create trigger auth_user_profile_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.protect_tariff_versions()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if tg_op in ('UPDATE', 'DELETE') then
    raise exception 'Tariff versions are immutable; create a new effective-dated version instead.';
  end if;
  return new;
end;
$$;

create trigger tariff_versions_are_immutable
before update or delete on public.tariff_versions
for each row execute function public.protect_tariff_versions();

create or replace function public.prevent_tariff_backdating()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  -- Serialize tariff applicability checks with monthly-bill validation.
  perform pg_advisory_xact_lock(1163284052);

  if exists (
    select 1
    from public.monthly_bills b
    where make_date(b.bill_year, b.bill_month, 1) >= new.effective_from
  ) then
    raise exception 'New tariff versions cannot take effect in or before a month that already has a saved bill.';
  end if;
  return new;
end;
$$;

create trigger tariff_versions_prevent_backdating
before insert on public.tariff_versions
for each row execute function public.prevent_tariff_backdating();

create or replace function public.validate_monthly_bill()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  tolerance constant numeric := 0.0001;
  expected_tariff_id uuid;
  stored_slabs jsonb;
  slab jsonb;
  person jsonb;
  slab_index integer;
  remaining_bill numeric := new.total_bill;
  slab_units numeric;
  slab_rate numeric;
  used numeric;
  used_units numeric[] := array[]::numeric[];
  slab_rates numeric[] := array[]::numeric[];
  expected_total_units numeric := 0;
  expected_ac_units numeric := 0;
  remaining_ac_units numeric;
  expected_ac_cost numeric := 0;
  expected_ac_rate numeric := 0;
  expected_shared_per_person numeric;
  people_count integer;
  reconciled_total numeric := 0;
  reconciled_ac_amount numeric := 0;
  reconciled_shared_amount numeric := 0;
begin
  -- Use the same transaction lock as tariff creation so concurrent writes
  -- cannot both validate against stale tariff applicability state.
  perform pg_advisory_xact_lock(1163284052);

  select id, slabs into expected_tariff_id, stored_slabs
  from public.tariff_versions
  where effective_from <= make_date(new.bill_year, new.bill_month, 1)
  order by effective_from desc
  limit 1;

  if expected_tariff_id is null or new.tariff_version_id <> expected_tariff_id then
    raise exception 'Monthly bills must use the latest tariff effective on or before the first day of the bill month.';
  end if;

  if stored_slabs <> new.tariff_snapshot then
    raise exception 'Tariff snapshot must exactly match the selected immutable tariff version.';
  end if;

  if jsonb_typeof(new.calculation_snapshot) <> 'object'
    or not (new.calculation_snapshot ?& array['total_units', 'ac_units', 'ac_cost', 'shared_per_person', 'capped'])
    or jsonb_typeof(new.calculation_snapshot -> 'total_units') <> 'number'
    or jsonb_typeof(new.calculation_snapshot -> 'ac_units') <> 'number'
    or jsonb_typeof(new.calculation_snapshot -> 'ac_cost') <> 'number'
    or jsonb_typeof(new.calculation_snapshot -> 'shared_per_person') <> 'number'
    or jsonb_typeof(new.calculation_snapshot -> 'capped') <> 'boolean' then
    raise exception 'Calculation snapshot is incomplete or invalid.';
  end if;

  if jsonb_typeof(new.people_snapshot) <> 'array'
    or jsonb_array_length(new.people_snapshot) = 0 then
    raise exception 'At least one calculated person is required.';
  end if;

  people_count := jsonb_array_length(new.people_snapshot);
  for person in select * from jsonb_array_elements(new.people_snapshot)
  loop
    if jsonb_typeof(person) <> 'object'
      or jsonb_typeof(person -> 'display_name') <> 'string'
      or jsonb_typeof(person -> 'public_alias') <> 'string'
      or nullif(btrim(person ->> 'display_name'), '') is null
      or nullif(btrim(person ->> 'public_alias'), '') is null
      or not (person ?& array['position', 'ac_units', 'ac_amount', 'shared_amount', 'total_amount'])
      or jsonb_typeof(person -> 'position') <> 'number'
      or jsonb_typeof(person -> 'ac_units') <> 'number'
      or jsonb_typeof(person -> 'ac_amount') <> 'number'
      or jsonb_typeof(person -> 'shared_amount') <> 'number'
      or jsonb_typeof(person -> 'total_amount') <> 'number'
      or (person ->> 'position')::numeric < 0
      or (person ->> 'position')::numeric > 2147483647
      or (person ->> 'position')::numeric <> trunc((person ->> 'position')::numeric)
      or (person ->> 'ac_units')::numeric < 0
      or (person ->> 'ac_amount')::numeric < 0
      or (person ->> 'shared_amount')::numeric < 0
      or (person ->> 'total_amount')::numeric < 0 then
      raise exception 'People snapshot contains an invalid row.';
    end if;
    expected_ac_units := expected_ac_units + (person ->> 'ac_units')::numeric;
  end loop;

  for slab_index in 0..jsonb_array_length(stored_slabs) - 1
  loop
    slab := stored_slabs -> slab_index;
    slab_rate := (slab ->> 'rate')::numeric;
    slab_units := case when jsonb_typeof(slab -> 'units') = 'null'
      then null else (slab ->> 'units')::numeric end;
    used := case when slab_units is null
      then remaining_bill / slab_rate
      else least(slab_units, remaining_bill / slab_rate) end;
    used := greatest(used, 0);
    used_units := array_append(used_units, used);
    slab_rates := array_append(slab_rates, slab_rate);
    expected_total_units := expected_total_units + used;
    remaining_bill := greatest(remaining_bill - used * slab_rate, 0);
  end loop;

  if remaining_bill > tolerance then
    raise exception 'Tariff snapshot cannot price the complete bill.';
  end if;
  if expected_ac_units > expected_total_units + tolerance then
    raise exception 'People AC units exceed the bill units.';
  end if;

  remaining_ac_units := expected_ac_units;
  slab_index := array_length(used_units, 1);
  while slab_index >= 1 and remaining_ac_units > tolerance
  loop
    used := least(remaining_ac_units, used_units[slab_index]);
    expected_ac_cost := expected_ac_cost + used * slab_rates[slab_index];
    remaining_ac_units := remaining_ac_units - used;
    slab_index := slab_index - 1;
  end loop;

  if expected_ac_units > tolerance then
    expected_ac_rate := expected_ac_cost / expected_ac_units;
  end if;
  expected_shared_per_person := (new.total_bill - expected_ac_cost) / people_count;

  if abs((new.calculation_snapshot ->> 'total_units')::numeric - expected_total_units) > tolerance
    or abs((new.calculation_snapshot ->> 'ac_units')::numeric - expected_ac_units) > tolerance
    or abs((new.calculation_snapshot ->> 'ac_cost')::numeric - expected_ac_cost) > tolerance
    or abs((new.calculation_snapshot ->> 'shared_per_person')::numeric - expected_shared_per_person) > tolerance
    or ((new.calculation_snapshot ->> 'capped')::boolean
      and abs(expected_ac_units - expected_total_units) > tolerance) then
    raise exception 'Calculation snapshot does not match the tariff algorithm.';
  end if;

  for person in select * from jsonb_array_elements(new.people_snapshot)
  loop
    if abs((person ->> 'ac_amount')::numeric
        - (person ->> 'ac_units')::numeric * expected_ac_rate) > tolerance
      or abs((person ->> 'shared_amount')::numeric - expected_shared_per_person) > tolerance
      or abs((person ->> 'total_amount')::numeric
        - (person ->> 'ac_amount')::numeric
        - (person ->> 'shared_amount')::numeric) > tolerance then
      raise exception 'People snapshot does not match the tariff calculation.';
    end if;
    reconciled_ac_amount := reconciled_ac_amount + (person ->> 'ac_amount')::numeric;
    reconciled_shared_amount := reconciled_shared_amount + (person ->> 'shared_amount')::numeric;
    reconciled_total := reconciled_total + (person ->> 'total_amount')::numeric;
  end loop;

  if abs(reconciled_ac_amount - expected_ac_cost) > tolerance
    or abs(reconciled_shared_amount - (new.total_bill - expected_ac_cost)) > tolerance
    or abs(reconciled_total - new.total_bill) > tolerance
    or abs(reconciled_total - reconciled_ac_amount - reconciled_shared_amount) > tolerance then
    raise exception 'Calculated person totals must reconcile to the monthly bill.';
  end if;

  if tg_op = 'INSERT' then
    if new.status <> 'draft' or new.published_at is not null then
      raise exception 'New monthly bills must start as drafts.';
    end if;
    new.created_by := auth.uid();
    new.created_at := now();
  else
    new.id := old.id;
    new.created_by := old.created_by;
    new.created_at := old.created_at;

    if old.status = 'published' then
      if new.status = 'published' then
        if (new.bill_year, new.bill_month, new.total_bill, new.tariff_version_id,
            new.tariff_snapshot, new.calculation_snapshot, new.people_snapshot)
          is distinct from
           (old.bill_year, old.bill_month, old.total_bill, old.tariff_version_id,
            old.tariff_snapshot, old.calculation_snapshot, old.people_snapshot) then
          raise exception 'Published bills are immutable. Reopen the bill before editing.';
        end if;
        new.published_at := old.published_at;
      elsif new.status = 'draft' then
        if (new.bill_year, new.bill_month, new.total_bill, new.tariff_version_id,
            new.tariff_snapshot, new.calculation_snapshot, new.people_snapshot)
          is distinct from
           (old.bill_year, old.bill_month, old.total_bill, old.tariff_version_id,
            old.tariff_snapshot, old.calculation_snapshot, old.people_snapshot) then
          raise exception 'Reopening and editing must be separate operations.';
        end if;
        new.published_at := null;
      end if;
    elsif old.status = 'draft' and new.status = 'published' then
      new.published_at := now();
    else
      new.published_at := null;
    end if;
  end if;

  new.updated_by := auth.uid();
  new.updated_at := now();
  return new;
exception
  when invalid_text_representation or numeric_value_out_of_range or division_by_zero then
    raise exception 'Monthly bill snapshots contain invalid numeric values.';
end;
$$;

create trigger monthly_bills_validate_changes
before insert or update on public.monthly_bills
for each row execute function public.validate_monthly_bill();

create or replace function public.write_audit_log()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  old_json jsonb;
  new_json jsonb;
  affected_id uuid;
begin
  old_json := case when tg_op in ('UPDATE', 'DELETE') then to_jsonb(old) else null end;
  new_json := case when tg_op in ('INSERT', 'UPDATE') then to_jsonb(new) else null end;
  affected_id := coalesce((new_json ->> 'id')::uuid, (old_json ->> 'id')::uuid);

  insert into public.audit_logs (actor_id, action, table_name, row_id, old_record, new_record)
  values (auth.uid(), tg_op, tg_table_name, affected_id, old_json, new_json);

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

create trigger profiles_audit
after insert or update or delete on public.profiles
for each row execute function public.write_audit_log();
create trigger tariff_versions_audit
after insert or update or delete on public.tariff_versions
for each row execute function public.write_audit_log();
create trigger monthly_bills_audit
after insert or update or delete on public.monthly_bills
for each row execute function public.write_audit_log();

-- The public view deliberately omits display_name. RLS alone cannot hide a key
-- nested inside JSON, so anonymous users receive only public aliases and totals.
create or replace view public.published_monthly_bills
with (security_barrier = true)
as
select
  b.id,
  b.bill_year,
  b.bill_month,
  b.total_bill,
  b.tariff_snapshot,
  b.calculation_snapshot,
  coalesce(public_people.people_snapshot, '[]'::jsonb) as people_snapshot,
  b.published_at
from public.monthly_bills b
cross join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'position', person -> 'position',
      'public_alias', person -> 'public_alias',
      'color', person -> 'color',
      'ac_units', person -> 'ac_units',
      'ac_amount', person -> 'ac_amount',
      'shared_amount', person -> 'shared_amount',
      'total_amount', person -> 'total_amount'
    ) order by (person ->> 'position')::integer
  ) as people_snapshot
  from jsonb_array_elements(b.people_snapshot) person
) public_people
where b.status = 'published';

alter table public.profiles enable row level security;
alter table public.tariff_versions enable row level security;
alter table public.monthly_bills enable row level security;
alter table public.audit_logs enable row level security;

create policy profiles_read_own_or_admin
on public.profiles for select
to authenticated
using (id = auth.uid() or public.is_admin());

create policy tariffs_public_read
on public.tariff_versions for select
to anon, authenticated
using (true);

create policy tariffs_admin_insert
on public.tariff_versions for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

create policy monthly_bills_admin_read
on public.monthly_bills for select
to authenticated
using (public.is_admin());

create policy monthly_bills_admin_insert
on public.monthly_bills for insert
to authenticated
with check (public.is_admin() and created_by = auth.uid());

create policy monthly_bills_admin_update
on public.monthly_bills for update
to authenticated
using (public.is_admin())
with check (public.is_admin());

create policy audit_logs_admin_read
on public.audit_logs for select
to authenticated
using (public.is_admin());

revoke all on public.profiles from anon, authenticated;
revoke all on public.tariff_versions from anon, authenticated;
revoke all on public.monthly_bills from anon, authenticated;
revoke all on public.audit_logs from anon, authenticated;
revoke all on public.published_monthly_bills from anon, authenticated;

grant select on public.profiles to authenticated;
grant select on public.tariff_versions to anon, authenticated;
grant insert on public.tariff_versions to authenticated;
grant usage, select on sequence public.tariff_versions_version_seq to authenticated;
grant select, insert, update on public.monthly_bills to authenticated;
grant select on public.audit_logs to authenticated;
grant select on public.published_monthly_bills to anon, authenticated;
grant execute on function public.is_admin() to anon, authenticated;

revoke execute on function public.validate_tariff_slabs(jsonb) from public;
revoke execute on function public.handle_new_user() from public;
revoke execute on function public.protect_tariff_versions() from public;
revoke execute on function public.prevent_tariff_backdating() from public;
revoke execute on function public.validate_monthly_bill() from public;
revoke execute on function public.write_audit_log() from public;

insert into public.tariff_versions (version, label, effective_from, slabs, created_by)
values (
  1,
  'Bundled residential default',
  date '2025-01-01',
  '[{"units":75,"rate":6.18},{"units":124,"rate":8.50},{"units":99,"rate":9.10},{"units":99,"rate":9.62},{"units":199,"rate":15.01},{"units":null,"rate":17.35}]'::jsonb,
  null
)
on conflict (effective_from) do nothing;

alter table public.tariff_versions alter column version restart with 2;
